// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Kin-dza-dzaa/wordApi/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddWords provides a mock function with given fields: ctx, words, userId
func (_m *Service) AddWords(ctx context.Context, words models.WordsToAdd, userId string) (map[string]string, error) {
	ret := _m.Called(ctx, words, userId)

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(context.Context, models.WordsToAdd, string) map[string]string); ok {
		r0 = rf(ctx, words, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.WordsToAdd, string) error); ok {
		r1 = rf(ctx, words, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteWords provides a mock function with given fields: ctx, words, userId
func (_m *Service) DeleteWords(ctx context.Context, words models.WordsToDelete, userId string) error {
	ret := _m.Called(ctx, words, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.WordsToDelete, string) error); ok {
		r0 = rf(ctx, words, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWords provides a mock function with given fields: ctx, words, userId
func (_m *Service) GetWords(ctx context.Context, words models.Words, userId string) error {
	ret := _m.Called(ctx, words, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Words, string) error); ok {
		r0 = rf(ctx, words, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateState provides a mock function with given fields: ctx, words, userId
func (_m *Service) UpdateState(ctx context.Context, words models.StatesToUpdate, userId string) error {
	ret := _m.Called(ctx, words, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.StatesToUpdate, string) error); ok {
		r0 = rf(ctx, words, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWord provides a mock function with given fields: ctx, words, userId
func (_m *Service) UpdateWord(ctx context.Context, words models.WordToUpdate, userId string) error {
	ret := _m.Called(ctx, words, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.WordToUpdate, string) error); ok {
		r0 = rf(ctx, words, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateToken provides a mock function with given fields: user
func (_m *Service) ValidateToken(user *models.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
